Repository JUNGYUN-Daegu/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#7 [FE] 개발 환경 설정 마무리 작업
  FE/issue-tracker/config-overrides.js
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/package.json
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/assets/LogotypeLarge.svg
  FE/issue-tracker/src/assets/LogotypeMedium.svg
  FE/issue-tracker/src/components/common/Header.tsx
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/index.tsx
  FE/issue-tracker/src/pages/IssueDetail.tsx
  FE/issue-tracker/src/pages/Issues.tsx
  FE/issue-tracker/src/pages/Labels.tsx
  FE/issue-tracker/src/pages/Login.tsx
  FE/issue-tracker/src/pages/MileStones.tsx
  FE/issue-tracker/src/pages/NewIssue.tsx
  FE/issue-tracker/src/store/atoms/test.ts
  FE/issue-tracker/src/store/selectors/test.ts
  FE/issue-tracker/src/styles/theme.js
  FE/issue-tracker/tsconfig.path.json
Labels: FE

#14 [FE] Header, Tabs 공통 컴포넌트 생성, theme에 스타일 추가
  FE/issue-tracker/public/janmang.jpeg
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/assets/edit.svg
  FE/issue-tracker/src/assets/milestone.svg
  FE/issue-tracker/src/assets/tag.svg
  FE/issue-tracker/src/assets/trash.svg
  FE/issue-tracker/src/components/common/Header.tsx
  FE/issue-tracker/src/components/common/Tabs.tsx
  FE/issue-tracker/src/pages/Labels.tsx
  FE/issue-tracker/src/styles/theme.js
Labels: FE

#15 [FE] Milestones 파일명 변경에 따른 App 파일 수정
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/pages/MileStones.tsx
Labels: FE

#16 [FE] 로그인 메인 페이지 UI 구현
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/components/common/Tabs.tsx
  FE/issue-tracker/src/components/login/Main.tsx
  FE/issue-tracker/src/components/login/style.ts
  FE/issue-tracker/src/pages/Login.tsx
Labels: FE, enhancement

#17 Refactor: 코드 리뷰 반영
  FE/issue-tracker/src/components/login/LoginMain.tsx
  FE/issue-tracker/src/pages/Login.tsx
Labels: FE

#19 [FE] 라벨 페이지 UI 구현
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/assets/cancel.svg
  FE/issue-tracker/src/assets/refresh.svg
  FE/issue-tracker/src/components/common/Header.tsx
  FE/issue-tracker/src/components/labels/Actions.tsx
  FE/issue-tracker/src/components/labels/Label.tsx
  FE/issue-tracker/src/components/labels/LabelInputBox.tsx
  FE/issue-tracker/src/components/labels/NewLabel.tsx
  FE/issue-tracker/src/components/labels/newLabelStyle.ts
  FE/issue-tracker/src/components/labels/table/EditLabel.tsx
  FE/issue-tracker/src/components/labels/table/LabelCell.tsx
  FE/issue-tracker/src/components/labels/table/LabelTable.tsx
  FE/issue-tracker/src/components/labels/table/TableHeader.tsx
  FE/issue-tracker/src/pages/Labels.tsx
Labels: FE, enhancement

#20 [FE] 이슈 목록 페이지 UI 구현
  FE/issue-tracker/src/assets/dropDown.svg
  FE/issue-tracker/src/assets/search.svg
  FE/issue-tracker/src/components/common/Header.tsx
  FE/issue-tracker/src/components/common/Label.tsx
  FE/issue-tracker/src/components/common/Tabs.tsx
  FE/issue-tracker/src/components/issues/Actions.tsx
  FE/issue-tracker/src/components/issues/FilterBar.tsx
  FE/issue-tracker/src/components/issues/IssueContainer.tsx
  FE/issue-tracker/src/components/issues/table/Issue.tsx
  FE/issue-tracker/src/components/issues/table/IssueTable.tsx
  FE/issue-tracker/src/components/issues/table/TableHeader.tsx
  FE/issue-tracker/src/components/issues/table/style.ts
  FE/issue-tracker/src/components/labels/LabelInputBox.tsx
  FE/issue-tracker/src/components/labels/table/LabelCell.tsx
  FE/issue-tracker/src/pages/Issues.tsx
Labels: FE, enhancement

#21 Fix: 파일명 오류로 인한 경로 변경
  FE/issue-tracker/src/pages/Milestones.tsx
Labels: FE

#26 [FE] 이슈 생성 페이지 UI 작업 마무리
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/assets/file.svg
  FE/issue-tracker/src/assets/plus.svg
  FE/issue-tracker/src/components/common/MenuTitle.tsx
  FE/issue-tracker/src/components/common/Skeleton.tsx
  FE/issue-tracker/src/components/issues/FilterBar.tsx
  FE/issue-tracker/src/components/issues/IssueContainer.tsx
  FE/issue-tracker/src/components/issues/table/TableHeader.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AssigneeFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/LabelFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/MilestoneFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeader.tsx
  FE/issue-tracker/src/components/issues/tableHeader/style.ts
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueTable.tsx
  FE/issue-tracker/src/components/login/LoginMain.tsx
  FE/issue-tracker/src/components/newIssue/ButtonBox.tsx
  FE/issue-tracker/src/components/newIssue/NewIssueContainer.tsx
  FE/issue-tracker/src/components/newIssue/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/SelectBox.tsx
  FE/issue-tracker/src/components/newIssue/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/SelectMilestone.tsx
  FE/issue-tracker/src/components/newIssue/TextBox.tsx
  FE/issue-tracker/src/components/newIssue/style.ts
  FE/issue-tracker/src/pages/Issues.tsx
  FE/issue-tracker/src/pages/NewIssue.tsx
  FE/issue-tracker/src/styles/chakraStyle.ts
Labels: FE, enhancement

#30 Import 경로 수정 반영
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/LabelFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/MilestoneFilter.tsx
  FE/issue-tracker/src/components/newIssue/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/SelectMilestone.tsx
Labels: FE

#31 chakraStyle Import 경로 에러 수정
  FE/issue-tracker/src/components/newIssue/SelectAssignee.tsx
Labels: FE

#33 [FE] IssueDetail 페이지 공통 컴포넌트 추가해서 완료, 리뷰 반영 리팩토링
  FE/issue-tracker/src/components/common/CloseMiniButton.tsx
  FE/issue-tracker/src/components/common/DeleteMiniButton.tsx
  FE/issue-tracker/src/components/common/EditCompleteBtn.tsx
  FE/issue-tracker/src/components/common/Header.tsx
  FE/issue-tracker/src/components/issueDetail/IssueSidebar.tsx
  FE/issue-tracker/src/components/issueDetail/NewComment.tsx
  FE/issue-tracker/src/components/labels/table/EditLabel.tsx
  FE/issue-tracker/src/components/labels/table/LabelCell.tsx
  FE/issue-tracker/src/components/labels/table/LabelTable.tsx
  FE/issue-tracker/src/components/milestones/table/EditMilestone.tsx
  FE/issue-tracker/src/components/milestones/table/MilestoneCell.tsx
  FE/issue-tracker/src/components/milestones/table/MilestoneTable.tsx
  FE/issue-tracker/src/pages/IssueDetail.tsx
  FE/issue-tracker/src/styles/theme.js
Labels: FE, enhancement

#45 [FE] 로그인 페이지 기능 구현
  FE/issue-tracker/.gitignore
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/package.json
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/components/login/LoginMain.tsx
  FE/issue-tracker/src/components/login/getAccessToken.ts
  FE/issue-tracker/src/components/login/style.ts
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/index.tsx
Labels: FE, enhancement

#47 [FE] issueList 코드리뷰 요청
  FE/issue-tracker/src/components/common/Label.tsx
  FE/issue-tracker/src/components/common/Skeleton.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeader.tsx
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueTable.tsx
  FE/issue-tracker/src/components/issues/tableMain/NoIssue.tsx
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/store/atoms/issueList.ts
Labels: FE, enhancement

#53 [FE] 이슈리스트 필터 기능 제외 데이터 요청 부분 마무리
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/src/components/issues/tableHeader/AssigneeFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/LabelFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/MilestoneFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeader.tsx
  FE/issue-tracker/src/components/issues/tableMain/ErrorIssueList.tsx
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueTable.tsx
  FE/issue-tracker/src/components/issues/tableMain/NoIssue.tsx
  FE/issue-tracker/src/components/login/queryString.d.ts
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/store/atoms/issueFilter.ts
  FE/issue-tracker/src/store/atoms/issueList.ts
  FE/issue-tracker/src/utils/fetchOnEnter.ts
  FE/issue-tracker/src/utils/pipe.ts
  FE/issue-tracker/src/utils/renderTimeText.ts
Labels: FE, enhancement

#56 [FE] 이슈 목록 페이지 변경 사항
  FE/issue-tracker/src/components/common/Skeleton.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeadLeft.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeader.tsx
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueList.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueTable.tsx
  FE/issue-tracker/src/store/atoms/issueList.ts
  FE/issue-tracker/src/utils/fetchOnEnter.ts
  FE/issue-tracker/src/utils/pipe.ts
  FE/issue-tracker/src/utils/query.ts
Labels: FE, enhancement

#57 [FE] 이슈 생성 페이지 SelectBox UI 수정, jwt 디코드, 에러 처리
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/package.json
  FE/issue-tracker/src/components/login/getAccessToken.ts
  FE/issue-tracker/src/components/login/style.ts
  FE/issue-tracker/src/components/newIssue/ButtonBox.tsx
  FE/issue-tracker/src/components/newIssue/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/SelectBox.tsx
  FE/issue-tracker/src/components/newIssue/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/SelectMilestone.tsx
  FE/issue-tracker/src/components/newIssue/TextBox.tsx
  FE/issue-tracker/src/components/newIssue/select/AssigneeModal.tsx
  FE/issue-tracker/src/components/newIssue/select/LabelModal.tsx
  FE/issue-tracker/src/components/newIssue/select/MilestoneModal.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectMilestone.tsx
  FE/issue-tracker/src/components/newIssue/style.ts
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/store/atoms/checkedThings.ts
  FE/issue-tracker/src/store/atoms/newIssue.ts
  FE/issue-tracker/src/styles/chakraStyle.ts
  FE/issue-tracker/src/utils/fetchModal.ts
Labels: FE

#60 [FE] 이슈 목록페이지
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/package.json
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/components/issues/Actions.tsx
  FE/issue-tracker/src/components/issues/FilterBar.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AssigneeFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/LabelFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/MilestoneFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/TableHeadLeft.tsx
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueList.tsx
  FE/issue-tracker/src/const/var.ts
  FE/issue-tracker/src/store/atoms/issueFilter.ts
  FE/issue-tracker/src/store/atoms/issueList.ts
  FE/issue-tracker/src/styles/chakraStyle.ts
  FE/issue-tracker/src/utils/fetchOnEnter.ts
  FE/issue-tracker/src/utils/fetchWithAuth.ts
Labels: FE, enhancement

#73 [FE] SelectBox 클릭에 따라 요소 렌더링
  FE/issue-tracker/src/components/login/LoginMain.tsx
  FE/issue-tracker/src/components/login/fetchToken.ts
  FE/issue-tracker/src/components/newIssue/select/AssigneeModal.tsx
  FE/issue-tracker/src/components/newIssue/select/LabelModal.tsx
  FE/issue-tracker/src/components/newIssue/select/MilestoneModal.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectMilestone.tsx
  FE/issue-tracker/src/store/atoms/checkedThings.ts
  FE/issue-tracker/src/store/atoms/login.ts
  FE/issue-tracker/src/utils/fetchModal.ts
Labels: FE, enhancement

#74 [FE] 이슈 목록페이지 필터 기능 및 상세페이지 편집 기능 추가
  FE/issue-tracker/src/App.tsx
  FE/issue-tracker/src/components/common/CommonTextArea.tsx
  FE/issue-tracker/src/components/common/CompleteBtn.tsx
  FE/issue-tracker/src/components/common/EditMiniButton.tsx
  FE/issue-tracker/src/components/issueDetail/Comment.tsx
  FE/issue-tracker/src/components/issueDetail/CommentBox.tsx
  FE/issue-tracker/src/components/issueDetail/IssueDetailTitle.tsx
  FE/issue-tracker/src/components/issueDetail/IssueHeader.tsx
  FE/issue-tracker/src/components/issueDetail/NewComment.tsx
  FE/issue-tracker/src/components/issueDetail/TextArea.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AssigneeFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/LabelFilter.tsx
  FE/issue-tracker/src/components/issues/tableHeader/MilestoneFilter.tsx
  FE/issue-tracker/src/components/issues/tableMain/Issue.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueList.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueTable.tsx
  FE/issue-tracker/src/components/labels/table/LabelCell.tsx
  FE/issue-tracker/src/components/milestones/table/MilestoneCell.tsx
  FE/issue-tracker/src/components/newIssue/TextBox.tsx
  FE/issue-tracker/src/components/newIssue/select/MilestoneModal.tsx
  FE/issue-tracker/src/components/newIssue/style.ts
  FE/issue-tracker/src/pages/IssueDetail.tsx
  FE/issue-tracker/src/store/atoms/issueDetail.ts
  FE/issue-tracker/src/store/atoms/issueList.ts
  FE/issue-tracker/src/styles/chakraStyle.ts
  FE/issue-tracker/src/utils/fetchModal.ts
  FE/issue-tracker/src/utils/fetchWithAuth.ts
  FE/issue-tracker/src/utils/query.ts
  FE/issue-tracker/src/utils/useFetch.ts
Labels: FE, enhancement

#76 [FE] 이슈 생성 페이지 구현 완료
  FE/issue-tracker/src/components/newIssue/ButtonBox.tsx
  FE/issue-tracker/src/components/newIssue/ContentsTextArea.tsx
  FE/issue-tracker/src/components/newIssue/TextBox.tsx
  FE/issue-tracker/src/components/newIssue/TitleInput.tsx
  FE/issue-tracker/src/components/newIssue/select/AssigneeModal.tsx
  FE/issue-tracker/src/components/newIssue/select/LabelModal.tsx
  FE/issue-tracker/src/components/newIssue/select/MilestoneModal.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectMilestone.tsx
  FE/issue-tracker/src/components/newIssue/style.ts
  FE/issue-tracker/src/pages/NewIssue.tsx
  FE/issue-tracker/src/store/atoms/checkedThings.ts
  FE/issue-tracker/src/store/atoms/newIssue.ts
  FE/issue-tracker/src/store/selectors/newIssue.ts
Labels: FE, enhancement

#78 [FE] 버그들 수정
  FE/issue-tracker/package-lock.json
  FE/issue-tracker/src/components/common/CommonTextArea.tsx
  FE/issue-tracker/src/components/issueDetail/CommentBox.tsx
  FE/issue-tracker/src/components/issueDetail/TextArea.tsx
  FE/issue-tracker/src/components/issues/tableHeader/AuthorFilter.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueList.tsx
  FE/issue-tracker/src/components/login/LoginMain.tsx
  FE/issue-tracker/src/components/login/fetchToken.ts
  FE/issue-tracker/src/components/newIssue/ButtonBox.tsx
  FE/issue-tracker/src/components/newIssue/ContentsTextArea.tsx
  FE/issue-tracker/src/components/newIssue/SelectBox.tsx
  FE/issue-tracker/src/components/newIssue/TitleInput.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectAssignee.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectLabel.tsx
  FE/issue-tracker/src/components/newIssue/select/SelectMilestone.tsx
  FE/issue-tracker/src/store/atoms/newIssue.ts
  FE/issue-tracker/src/store/selectors/newIssue.ts
  FE/issue-tracker/src/utils/useFetch.ts
Labels: FE, bug

#80 이슈 삭제와 상태 변경 부분 추가
  FE/issue-tracker/src/components/issueDetail/CommentBox.tsx
  FE/issue-tracker/src/components/issueDetail/IssueHeader.tsx
  FE/issue-tracker/src/components/issueDetail/IssueSidebar.tsx
  FE/issue-tracker/src/components/issues/tableMain/IssueList.tsx
Labels: FE, enhancement
